# yamllint disable
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "ps225_sriov_netdevice",
                "selectors": {
                    "vendors": ["14e4"],
                    "devices": ["d800"],
                    "drivers": ["bnxt_en"],
                    "pfNames": ["enp8s0f0np0"]
                }
            },
            {
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c"],
                    "drivers": ["i40evf"],
                    "pfNames": ["enp12s0f0"]
                }
            }
        ]
    }
